### ISSUE TITLE
Project compileert niet

### ISSUE THREAD

**Issue by cniekel** [berthubert/tkconv#1]
Hoi!

Na al jouw mooie plaatjes op mastodon dacht ik het eens uit te proberen.

`subprojects/sqlwriter.wrap heeft 'revision head', maar dat geeft errors. Ik heb het in 'main' veranderd, misschien werkt 'HEAD' ook.

Als ik cd builddir; meson compile doe, of ninja, kan de sqlwriter.hh niet gevonden worden.

```
[14/22] Compiling C++ object tkdisco.p/tkdisco.cc.o                                                                                           
FAILED: tkdisco.p/tkdisco.cc.o                                                                                                                
c++ -Itkdisco.p -I. -I.. -I../subprojects/fmt-10.1.1/include -Isubprojects/cpp-httplib-0.13.1 -I../subprojects/cpp-httplib-0.13.1 -I../subprojects/argparse-3.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++20 -g -pthread -DCPPHTTPLIB_OPENSSL_SUPPORT -DCPPHTTPLIB_ZLIB_SUPPORT -DCPPHTTPLIB_BROTLI_SUPPORT -MD -MQ tkdisco.p/tkdisco.cc.o -MF tkdisco.p/tkdisco.cc.o.d -o tkdisco.p/tkdisco.cc.o -c ../tkdisco.cc                                                                                                       
../tkdisco.cc:6:10: fatal error: sqlwriter.hh: No such file or directory                                                                          
6 | #include "sqlwriter.hh"                                                                                                               
   |          ^~~~~~~~~~~~~~                                                                                                               
compilation terminated.
```

En inderdaad, `../subprojects/sqlwriter` staat er niet in the c++ flags. Die directory is er wel (en er is een sqlwriter.hh file), maar meson heeft 'm niet aan de compiler flags toegevoegd. 
De dependencies in meson.build zagen er goed uit, dus ik had geen idee hoe verder te gaan.

**Comment by berthubert** [comment]
Hoi cniekel,

Fijn dat je meedoet, en gefeliciteerd met issue #1!

Welke versie van meson is dit mee? En welk OS? Kan je het begin van de meson setup stap delen?

**Comment by cniekel** [comment]
Hmm, het is meson 0.61.2, en komt van ubuntu jammy (uit 2022-4).
Ik zie dat meson inmiddels al op 1.6 zit, dus ik zal eerst eens een minder oud OS gaan maken.

**Comment by peterpeerdeman** [comment]
@cniekel ik heb een aanzet gedaan voor het toevoegen van een docker file waar ook de dependencies voorgeinstalleerd worden en je binnen een docker container kunt compileren. wellicht kan dat je op weg helpen: https://github.com/berthubert/tkconv/pull/4

**Comment by cniekel** [comment]
Eindelijk tijd gemaakt, ubuntu geupgrade, en nu werkt het!
