### ISSUE TITLE
Verschillende termen uit de MvT bij begroting EZK worden niet gevonden. 

### ISSUE THREAD

**Issue by Internetthought** [berthubert/tkconv#15]
Ik weet niet of het een bug is, of een feature, omdat je niet alles kunt indexeren. Maar goed: 

De Memorie van Toelichting van EZK bij de begroting 2025 heeft een stuk tekst over de "Gigabit Infrastructure Act". De Tweede Kamer komt met de MvT wanneer ik zoek op deze drie woorden. https://www.tweedekamer.nl/zoeken?qry=gigabit%20infrastructure%20act&cfg=tksearch&sta=1&srt=date%3Adesc%3Adate 

Het meest recente resultaat is document 2024D31100 onder het kopje Overige Kamerstukken17 september 2024

Op TKconv leidt een zoekactie op document https://berthub.eu/tkconv/get/2024D31100 naar een redirect die niet goed lijkt te gaan. 

Echter, zowel zoeken op Gigabit Infrastructure Act, 5G, glasvezel en dergelijke leveren allemaal geen verwijzing op naar de MvT bij de begroting. 

https://www.tweedekamer.nl/zoeken?qry=glasvezel&cfg=tksearch&sta=1&srt=date%3Adesc%3Adate
https://berthub.eu/tkconv/search.html?q=glasvezel&twomonths=false

https://berthub.eu/tkconv/search.html?q=5G&twomonths=false
https://www.tweedekamer.nl/zoeken?qry=5G&cfg=tksearch&sta=1&srt=date%3Adesc%3Adate

Wat me ook opviel is dat de MvT bij de begroting van andere ministeries waarin 5G ook wordt genoemd wel worden gevonden. Om de meest recente documenten te vinden dient dan wel het vakje voor 2 maanden te worden aangevinkt. 
https://berthub.eu/tkconv/search.html?q=5G&twomonths=false levert als meest recente stuk een antwoord op kamervraag van 25 april 2024 over satellietstation Burum 
https://berthub.eu/tkconv/search.html?q=5G&twomonths=true geeft als meest recente document een document van 23 september [2024D34552](https://berthub.eu/tkconv/get/2024D34552)

**Comment by berthubert** [comment]
http://127.0.0.1:4321/search.html?q=+%22Gigabit+Infrastructure+Act%22&twomonths=false en nu vindt hij hem
