### ISSUE TITLE
Verzoek: RSS feed aan query

### ISSUE THREAD

**Issue by eiland-asbl** [berthubert/tkconv#21]
Zou jee aardige feature zijn om aan bv. https://berthub.eu/tkconv/search.html?q=mijnbouw&twomonths=true&soorten=alles een rss feed te koppelen.

**Comment by Sjors** [comment]
Bijkomende voordelen:
1. Betere privacy (site weet toch je IP al, maar heeft niet je email nodig)
2. Handig om een (Telegram, Twitter, Mastodon, Nostr) bot te maken voor een specifiek onderwerp.

**Comment by berthubert** [comment]
heb inmiddels wat voorbereidingen getroffen waardoor dit makkelijker wordt, maar uitdaging is wel dat sommige queries seconden rekenen vergen, en RSS readers nogal veel langskomen. Ik puzzel daarom aan wat optimalisaties dat de zoekslag alleen gemaakt wordt als er nieuwe documenten zijn. Work in progress!

**Comment by berthubert** [comment]
Het is nu live, kunnen jullie testen of dit doet wat je wil? Je moet mogelijk een shift-reload doen om de nieuwe javascript te krijgen. Op de zoekpagina hoort nu een RSS icoon te verschijnen.

**Comment by Sjors** [comment]
Dank! Wat eerste observaties a.d.h.v https://berthub.eu/tkconv/search/index.xml?q=onderuitputting

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<lastBuildDate>Thu, 12 Dec 2024 12:04:45 +0100</lastBuildDate>
<title>Zoek RSS</title>
<description>Documenten gematched door zoekstring onderuitputting</description>
<link>https://berthub.eu/tkconv/</link>
<generator>OpenTK</generator>
<item>
<title>Verslag houdende een lijst van vragen en antwoorden</title>
<description>vaste commissie voor Buitenlandse Zaken | Wijziging van de begrotingsstaat van het Ministerie van Buitenlandse Zaken (V) voor het jaar 2024 (wijziging samenhangende met Najaarsnota) Verslag houdende een lijst van vragen en antwoorden</description>
<link>https://berthub.eu/tkconv/document.html?nummer=2024D48768</link>
<guid>2024D48768</guid>
<pubDate>Thu, 12 Dec 2024 12:04:45 +0100</pubDate>
</item>
...
```

* link (van de `<channel>`) zou ook de query kunnen bevatten
* `guid`: ik weet niet of die globaal uniek horen te zijn, of alleen voor de feed?

Verder lijkt het goed te werken, ik zie i.i.g. `304 Not Modified` en `etag`.

**Comment by Sjors** [comment]
In de NetNewsWire RSS reader ziet er ook prima uit.

**Comment by berthubert** [comment]
Ik heb de GUID nog voorzien van een prefix zodat ie iets meer globally unique is. En dan moet het maar zo. Dank voor de suggestie!

**Comment by eiland-asbl** [comment]
Ik zou de snip ook in de rss feed zetten, en de titel van de feed dekt de lading niet heel goed? "Zoek RSS naar [trefwoord]"
