### ISSUE TITLE
[bug] Monitor verkeerde hit

### ISSUE THREAD

**Issue by AbelLykens** [berthubert/tkconv#41]
Mijn monitor voor "open source" (incl quotes) raakte op:
https://berthub.eu/tkconv/document.html?nummer=2024D51945

Dat zie ik in de pdf niet terug. Bugje?

**Comment by bitkat** [comment]
Jawel, staat op p14 
![image](https://github.com/user-attachments/assets/320b202d-6d8d-48b6-acee-267e81f1b4cf)

**Comment by AbelLykens** [comment]
Oh "open source" matcht ook met een streepje er tussen, interesting.

**Comment by AbelLykens** [comment]
Als dit OK/verwacht is dan sluiten @berthubert ?

**Comment by berthubert** [comment]
Graag!
