### ISSUE TITLE
tkserv and tkgetxml reageren niet op ctrl+c of ctrl+d om netjes af te sluiten

### ISSUE THREAD

**Issue by peterpeerdeman** [berthubert/tkconv#6]
terwijl ik bezig was met het draaien van de bovenstaande commando's viel me op dat ik deze niet kon afsluiten met ctrl+c of ctrl+d, en moet ik steeds het process killen vanuit een andere tab. Dit is vooral vervelend bij het gebruiken/debuggen van tkserv, die continu blijft draaien

**Comment by berthubert** [comment]
kan je dit reproduceren buiten docker? met name voor tkgetxml is dit heel onverwacht gedrag.
